
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CA_生成卡牌 : CardAction
{
    public CA_生成卡牌(JSONNode _buf)  : base(_buf) 
    {
    }

    public static CA_生成卡牌 DeserializeCA_生成卡牌(JSONNode _buf)
    {
        return new CA_生成卡牌(_buf);
    }

   
    public const int __ID__ = -2095094051;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

