
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CardData : Luban.BeanBase
{
    public CardData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
    }

    public static CardData DeserializeCardData(JSONNode _buf)
    {
        return new CardData(_buf);
    }

    /// <summary>
    /// 唯一标识符
    /// </summary>
    public readonly string ID;
    /// <summary>
    /// 卡牌名称
    /// </summary>
    public readonly string Name;
   
    public const int __ID__ = 55917306;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "}";
    }
}
}

