
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CardData : Luban.BeanBase
{
    public CardData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (CardType)_buf["type"].AsInt; }
        { if(!_buf["tag"].IsNumber) { throw new SerializationException(); }  Tag = (CardTag)_buf["tag"].AsInt; }
        { if(!_buf["price"].IsNumber) { throw new SerializationException(); }  Price = _buf["price"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
    }

    public static CardData DeserializeCardData(JSONNode _buf)
    {
        return new CardData(_buf);
    }

    /// <summary>
    /// 唯一标识符
    /// </summary>
    public readonly string ID;
    /// <summary>
    /// 卡牌名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 卡牌类型
    /// </summary>
    public readonly CardType Type;
    /// <summary>
    /// 卡牌标签
    /// </summary>
    public readonly CardTag Tag;
    /// <summary>
    /// 价格（购买和卖出）
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 描述（俺寻思）
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = 55917306;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "tag:" + Tag + ","
        + "price:" + Price + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

