
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 卡牌效果
/// </summary>
public abstract partial class CardAction : Luban.BeanBase
{
    public CardAction(JSONNode _buf) 
    {
    }

    public static CardAction DeserializeCardAction(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "CA_生成卡牌": return new CA_生成卡牌(_buf);
            case "CA_销毁自身": return new CA_销毁自身(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

