
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class CardEventDataTable
{
    private readonly System.Collections.Generic.Dictionary<string, CardEventData> _dataMap;
    private readonly System.Collections.Generic.List<CardEventData> _dataList;
    
    public CardEventDataTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, CardEventData>(count);
        _dataList = new System.Collections.Generic.List<CardEventData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CardEventData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.CardEventData.DeserializeCardEventData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, CardEventData> DataMap => _dataMap;
    public System.Collections.Generic.List<CardEventData> DataList => _dataList;

    public CardEventData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CardEventData Get(string key) => _dataMap[key];
    public CardEventData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

