
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CardEvent : Luban.BeanBase
{
    public CardEvent(JSONNode _buf) 
    {
        { if(!_buf["cardId"].IsString) { throw new SerializationException(); }  CardId = _buf["cardId"]; }
        { if(!_buf["triggerType"].IsNumber) { throw new SerializationException(); }  TriggerType = (CardEventType)_buf["triggerType"].AsInt; }
        { var __json0 = _buf["actions"]; if(!__json0.IsArray) { throw new SerializationException(); } Actions = new System.Collections.Generic.List<CardAction>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { CardAction __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.CardAction.DeserializeCardAction(__e0);  }  Actions.Add(__v0); }   }
    }

    public static CardEvent DeserializeCardEvent(JSONNode _buf)
    {
        return new CardEvent(_buf);
    }

    /// <summary>
    /// 触发者
    /// </summary>
    public readonly string CardId;
    /// <summary>
    /// 触发类型
    /// </summary>
    public readonly CardEventType TriggerType;
    /// <summary>
    /// 触发效果
    /// </summary>
    public readonly System.Collections.Generic.List<CardAction> Actions;
   
    public const int __ID__ = 1734971722;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Actions) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "cardId:" + CardId + ","
        + "triggerType:" + TriggerType + ","
        + "actions:" + Luban.StringUtil.CollectionToString(Actions) + ","
        + "}";
    }
}
}

