
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Recipe : Luban.BeanBase
{
    public Recipe(JSONNode _buf) 
    {
        { var __json0 = _buf["inputList"]; if(!__json0.IsArray) { throw new SerializationException(); } InputList = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  InputList.Add(__v0); }   }
        { var __json0 = _buf["outputList"]; if(!__json0.IsArray) { throw new SerializationException(); } OutputList = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  OutputList.Add(__v0); }   }
        { if(!_buf["workTime"].IsNumber) { throw new SerializationException(); }  WorkTime = _buf["workTime"]; }
    }

    public static Recipe DeserializeRecipe(JSONNode _buf)
    {
        return new Recipe(_buf);
    }

    /// <summary>
    /// 配方列表
    /// </summary>
    public readonly System.Collections.Generic.List<string> InputList;
    /// <summary>
    /// 产品列表
    /// </summary>
    public readonly System.Collections.Generic.List<string> OutputList;
    /// <summary>
    /// 配方时间
    /// </summary>
    public readonly float WorkTime;
   
    public const int __ID__ = -1851047506;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "inputList:" + Luban.StringUtil.CollectionToString(InputList) + ","
        + "outputList:" + Luban.StringUtil.CollectionToString(OutputList) + ","
        + "workTime:" + WorkTime + ","
        + "}";
    }
}
}

