
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class RecipeDataTable
{
    private readonly System.Collections.Generic.Dictionary<string, RecipeData> _dataMap;
    private readonly System.Collections.Generic.List<RecipeData> _dataList;
    
    public RecipeDataTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, RecipeData>(count);
        _dataList = new System.Collections.Generic.List<RecipeData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            RecipeData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.RecipeData.DeserializeRecipeData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, RecipeData> DataMap => _dataMap;
    public System.Collections.Generic.List<RecipeData> DataList => _dataList;

    public RecipeData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RecipeData Get(string key) => _dataMap[key];
    public RecipeData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

