
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class RecipeData : Luban.BeanBase
{
    public RecipeData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { var __json0 = _buf["inputList"]; if(!__json0.IsArray) { throw new SerializationException(); } InputList = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  InputList.Add(__v0); }   }
        { if(!_buf["isStrict"].IsBoolean) { throw new SerializationException(); }  IsStrict = _buf["isStrict"]; }
        { if(!_buf["workTime"].IsNumber) { throw new SerializationException(); }  WorkTime = _buf["workTime"]; }
        { var __json0 = _buf["actions"]; if(!__json0.IsArray) { throw new SerializationException(); } Actions = new System.Collections.Generic.List<CardAction>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { CardAction __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.CardAction.DeserializeCardAction(__e0);  }  Actions.Add(__v0); }   }
    }

    public static RecipeData DeserializeRecipeData(JSONNode _buf)
    {
        return new RecipeData(_buf);
    }

    /// <summary>
    /// 唯一标识符
    /// </summary>
    public readonly string ID;
    /// <summary>
    /// 配方列表
    /// </summary>
    public readonly System.Collections.Generic.List<string> InputList;
    /// <summary>
    /// 严格按照配方顺序
    /// </summary>
    public readonly bool IsStrict;
    /// <summary>
    /// 配方时间
    /// </summary>
    public readonly float WorkTime;
    /// <summary>
    /// 触发效果
    /// </summary>
    public readonly System.Collections.Generic.List<CardAction> Actions;
   
    public const int __ID__ = 1641487992;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Actions) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "inputList:" + Luban.StringUtil.CollectionToString(InputList) + ","
        + "isStrict:" + IsStrict + ","
        + "workTime:" + WorkTime + ","
        + "actions:" + Luban.StringUtil.CollectionToString(Actions) + ","
        + "}";
    }
}
}

