
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CA_生成卡牌 : CardAction
{
    public CA_生成卡牌(JSONNode _buf)  : base(_buf) 
    {
        { var __json0 = _buf["targetIds"]; if(!__json0.IsArray) { throw new SerializationException(); } TargetIds = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  TargetIds.Add(__v0); }   }
        { if(!_buf["isRandom"].IsBoolean) { throw new SerializationException(); }  IsRandom = _buf["isRandom"]; }
        { if(!_buf["amount"].IsNumber) { throw new SerializationException(); }  Amount = _buf["amount"]; }
    }

    public static CA_生成卡牌 DeserializeCA_生成卡牌(JSONNode _buf)
    {
        return new CA_生成卡牌(_buf);
    }

    /// <summary>
    /// 产品卡牌列表
    /// </summary>
    public readonly System.Collections.Generic.List<string> TargetIds;
    /// <summary>
    /// 随机生成
    /// </summary>
    public readonly bool IsRandom;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Amount;
   
    public const int __ID__ = -2095094051;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "targetIds:" + Luban.StringUtil.CollectionToString(TargetIds) + ","
        + "isRandom:" + IsRandom + ","
        + "amount:" + Amount + ","
        + "}";
    }
}
}

