
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class CardDataTable
{
    private readonly System.Collections.Generic.Dictionary<string, CardData> _dataMap;
    private readonly System.Collections.Generic.List<CardData> _dataList;
    
    public CardDataTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, CardData>(count);
        _dataList = new System.Collections.Generic.List<CardData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CardData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.CardData.DeserializeCardData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, CardData> DataMap => _dataMap;
    public System.Collections.Generic.List<CardData> DataList => _dataList;

    public CardData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CardData Get(string key) => _dataMap[key];
    public CardData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

